#!/bin/bash
source ~/lfs_packaging/base-funcs.sh
source ~/lfs_packaging/base-version.sh
source ~/lfs_packaging/arch.sh
source ~/lfs_packaging/distro.sh
source ~/lfs_packaging/uver.sh
source ~/lfs_packaging/version-checks.sh
source ~/lfs_packaging/freedesktop-components.sh
source ~/lfs_packaging/freedesktop.sh
source ~/lfs_packaging/github-components.sh
source ~/lfs_packaging/github.sh
source ~/lfs_packaging/gitlab-components.sh
source ~/lfs_packaging/gitlab.sh
source ~/lfs_packaging/gnome-components.sh
source ~/lfs_packaging/gnome.sh
source ~/lfs_packaging/gnu-components.sh
source ~/lfs_packaging/gnu.sh
source ~/lfs_packaging/glpk.sh
source ~/lfs_packaging/ngnu-components.sh
source ~/lfs_packaging/ngnu.sh
source ~/lfs_packaging/sourceforge-components.sh
source ~/lfs_packaging/sourceforge.sh
source ~/lfs_packaging/sourceware-components.sh
source ~/lfs_packaging/sourceware.sh
source ~/lfs_packaging/kde.sh
source ~/lfs_packaging/bitbucket-components.sh
source ~/lfs_packaging/bitbucket.sh
source ~/lfs_packaging/salsa-components.sh
source ~/lfs_packaging/salsa.sh
source ~/lfs_packaging/perl-components.sh
source ~/lfs_packaging/perl.sh
source ~/lfs_packaging/codeberg-components.sh
source ~/lfs_packaging/codeberg.sh
source ~/lfs_packaging/add_deps.sh
source ~/lfs_packaging/compile.sh
source ~/lfs_packaging/download.sh
source ~/lfs_packaging/prepare.sh
source ~/lfs_packaging/arch-copy.sh