# Asia
#server 0.asia.pool.ntp.org

# Australia
#server 0.oceania.pool.ntp.org

# Europe
#server 0.europe.pool.ntp.org

# North America
#server 0.north-america.pool.ntp.org

# South America
#server 2.south-america.pool.ntp.org

#driftfile /var/lib/ntp/ntp.drift
#pidfile   /run/ntpd.pid
server 0.oceania.pool.ntp.org iburst
server 1.oceania.pool.ntp.org iburst
server 2.oceania.pool.ntp.org iburst
server 3.oceania.pool.ntp.org iburst

driftfile /var/lib/ntp/ntp.drift
pidfile /run/ntpd.pid
